line-length = 100
target-version = "py312"

[lint]
select = ["F", "E", "W", "I", "UP", "B", "C4", "SIM", "RUF", "PL", "PT", "DTZ", "PIE", "PERF", "FLY", "ISC", "RET", "FURB", "EXE"]
ignore = ["E501", "BLE001", "S110"]
external = ["ARG", "N", "S", "E501", "BLE001", "S110"]

[format]
quote-style = "double"
